12:45:47.207 [main] INFO  testCases.TC_Blank_login__003 - === TC_Blank_Login_003 Started ===
12:45:48.272 [main] INFO  testCases.TC_Blank_login__003 - Navigated to URL: https://opensource-demo.orangehrmlive.com/
12:45:48.272 [main] INFO  testCases.TC_Blank_login__003 - Clicking login button without entering credentials
12:45:48.771 [main] INFO  testCases.TC_Blank_login__003 - Validating error message: Expected='Required' | Actual='true'
12:45:48.771 [main] ERROR testCases.TC_Blank_login__003 - Blank login validation failed
java.lang.AssertionError: Error message did not match for blank login! expected [Required] but found [true]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.assertEqualsImpl(Assert.java:150) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.assertEquals(Assert.java:132) ~[testng-7.9.0.jar:7.9.0]
	at testCases.TC_Blank_login__003.verifyBlankLogin(TC_Blank_login__003.java:46) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.9.0.jar:7.9.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:819) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestRunner.run(TestRunner.java:619) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.runSuites(TestNG.java:1134) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.run(TestNG.java:1101) [testng-7.9.0.jar:7.9.0]
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115) [testng-remote.jar:?]
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293) [testng-remote.jar:?]
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91) [testng-remote.jar:?]
12:54:05.687 [main] INFO  testCases.TC_Blank_login__003 - === TC_Invalid_Login_004 Started ===
12:54:07.022 [main] INFO  testCases.TC_Blank_login__003 - Navigated to URL: https://opensource-demo.orangehrmlive.com/
12:54:07.103 [main] INFO  testCases.TC_Blank_login__003 - Entering invalid username: wrong_user
12:54:08.104 [main] INFO  testCases.TC_Blank_login__003 - Entering invalid password: wrong_pass
12:54:08.558 [main] INFO  testCases.TC_Blank_login__003 - Clicking login button with invalid credentials
12:54:10.455 [main] INFO  testCases.TC_Blank_login__003 - Validating error message: Expected='Epic sadface: Username and password do not match any user in this service' | Actual='Invalid credentials'
12:54:10.487 [main] ERROR testCases.TC_Blank_login__003 - Invalid login validation failed
java.lang.AssertionError: Error message did not match for invalid login! expected [Epic sadface: Username and password do not match any user in this service] but found [Invalid credentials]
	at org.testng.Assert.fail(Assert.java:111) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.failNotEquals(Assert.java:1578) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.assertEqualsImpl(Assert.java:150) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.assertEquals(Assert.java:132) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.Assert.assertEquals(Assert.java:656) ~[testng-7.9.0.jar:7.9.0]
	at testCases.TC_Blank_login__003.verifyInvalidLogin(TC_Blank_login__003.java:57) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148) ~[testng-7.9.0.jar:7.9.0]
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.9.0.jar:7.9.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:819) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestRunner.run(TestRunner.java:619) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:336) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-7.9.0.jar:7.9.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.runSuites(TestNG.java:1134) [testng-7.9.0.jar:7.9.0]
	at org.testng.TestNG.run(TestNG.java:1101) [testng-7.9.0.jar:7.9.0]
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115) [testng-remote.jar:?]
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293) [testng-remote.jar:?]
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91) [testng-remote.jar:?]
